BEGIN TRANSACTION;
CREATE TABLE "news" ("Id" INTEGER,"Name" VARCHAR,"Description" VARCHAR,"DateStart" INTEGER DEFAULT (null) ,"DateFinish" INTEGER DEFAULT (null) , "Path" VARCHAR, "isAsset" INTEGER);
INSERT INTO `news` VALUES (2,'Testowy news','Mega Hot roll',1440972000000,1443650399000,'2.jpg',1);
INSERT INTO `news` VALUES (3,'Wielka afera','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus elit lacus, facilisis eget nulla non, venenatis ornare turpis. Nullam dignissim sapien a turpis sollicitudin, sit amet molestie mi aliquet. Quisque odio ligula, pharetra et mauris eu, hendrerit cursus arcu. Pellentesque quis lectus sit amet lacus sollicitudin malesuada. Nulla facilisi. Aenean non tortor et quam ultricies tincidunt quis sit amet risus. Aliquam sed sem dignissim, mattis turpis eu, eleifend mi. Pellentesque tincidunt dignissim quam, in dapibus eros dapibus ac. Aliquam pharetra nisi ac elit mattis imperdiet sed in nisi.

Sed lacinia in nunc a vulputate. Nunc lorem lectus, accumsan et pretium eu, consequat non erat. Etiam neque erat, venenatis a nibh non, egestas consectetur mauris. Integer iaculis leo libero, in imperdiet magna bibendum sit amet. Fusce ac metus eget leo rutrum aliquam. In hac habitasse platea dictumst. Phasellus posuere erat in pharetra sollicitudin. Sed sit amet urna eget lectus malesuada consectetur eget eget felis. Donec ullamcorper sapien nec ipsum ultrices dapibus. In a ligula quis magna feugiat cursus. Sed malesuada ipsum sit amet libero consectetur scelerisque. Maecenas in diam in massa placerat porttitor eget elementum orci. Suspendisse egestas, felis ut gravida ultrices, elit lorem pulvinar eros, sed gravida enim tellus non diam. Vestibulum lacinia mauris a risus porttitor, laoreet feugiat arcu fermentum. Aenean nec gravida magna, maximus placerat arcu. Curabitur id magna augue.

Cras lobortis augue ut sapien tincidunt vehicula non in nisl. Sed et ligula id purus varius dignissim. Curabitur laoreet lobortis egestas. Donec a velit eget risus venenatis placerat. Nam vitae purus diam. Cras eu lacus sapien. Mauris non urna lobortis, vehicula turpis nec, interdum mi. Etiam enim mi, lobortis et nulla ut, venenatis cursus risus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin at lorem faucibus, maximus mi quis, convallis arcu. Nam gravida malesuada dui eu posuere. Ut fringilla leo sed lorem viverra, et venenatis dui hendrerit. Nunc dictum porttitor lobortis. Sed congue sit amet neque at lacinia. Integer eu libero euismod, tincidunt sapien a, condimentum magna.',1440972000000,1443650399000,'1.jpg',1);
COMMIT;
